version: '3'
services:
  graphql-server:
    build: .
    ports:
      - "4000:4000"
    environment:
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
    volumes:
      - .:/app